### ISSUE TITLE
ByteCode and other IR support

### ISSUE THREAD

**Issue by sirinath** [xen2/SharpLang#37]
Is it possible to widen the scope so that this can support other IR / ByteCode formats easily. Also easy ability to construct language specific AST interpretors.

**Comment by tritao** [comment]
What other IR formats are you considering?

AFAIK this project is focused on .NET compatibility, if you want something general higher-purpose you could take the SharpLLVM bindings and start from there.

**Comment by sirinath** [comment]
I guess supporting JVM would be easy as the IR are similar. May be convert other formats like ParrotVM, Python, etc.

**Comment by xen2** [comment]
That won't be done as part of this project (or very long term). First focus is to have solid C#/MSIL implementation before moving on to anything else.
However, as @tritao mentionned, feel free to use SharpLLVM as a starting point.
