### ISSUE TITLE
Release SharpLLVM.Native and SharpLLVM

### ISSUE THREAD

**Issue by amerkoleci** [xen2/SharpLang#39]
Would be good to have thoose released (nightly build maybe) as it takes lot of amount to compile then both x64, x86 takes lot of time to compile and lot of disk usage.

Would this be possible?

Thanks

**Comment by xen2** [comment]
That should be done as part of #51.

However, to make sure, you are only interested in SharpLLVM (LLVM bindings), not SharpLang?

If yes, that means you likely want to use SharpLLVM library as part of another LLVM project as a developer, and in that case you probably want to compile it yourself to have debug symbols pointing to your LLVM sources (much easier to debug). Note that SharpLLVM don't get updated that often.

**Comment by amerkoleci** [comment]
I would use them in sharplang of course, everytime i need to recompile native part is such a pain and takes amount of time

**Comment by xen2** [comment]
Ha, so you would like to still be able to compile SharpLang, with pre-compiled SharpLLVM?

**Comment by amerkoleci** [comment]
Yes, the native part for me is pain, even if its not updated very much but every time it takes me 20-25 minutes to compile and the occupation (as you mentioned) is 14gb + 14 gb now for x64.

**Comment by xen2** [comment]
I see, thanks for the clarification.

Usually this is a one-time operation (LLVM is not updated often).
SharpLLVM might be updated but it can compile quickly.
But I agree it can be annoying and time consuming for first time setup.

Anyway, if it doesn't bother you to not have valid debug symbols, as soon as #51 is released, nothing prevent you from downloading prebuilt binaries.

**Comment by amerkoleci** [comment]
Agree with you, that will solve this issue. Closing now
